contract_address = "erd1qqqqqqqqqqqqqpgq4f6lm4mppra83zrz5r68f8ysutx7xqlrd8ssu2a8gu"
pair_address = "erd1qqqqqqqqqqqqqpgqf6gygvccj4dsxr4qj6v7ssfyvuq2nkuhd8ss8sa577"
energy_factory_address = "erd1qqqqqqqqqqqqqpgq59k00lhu335g6h0q894pz38uuk3ddmjwd8ssxtd8wr"
lp_farm_address = "erd1qqqqqqqqqqqqqpgqncc4kv32u4ptyu6fpw0qas226ede3w04d8ssmpaq05"
farm_staking_address = "erd1qqqqqqqqqqqqqpgqr783gdmmwduu2n4khj9nwfqfn6y8mzfud8ss4pf655"
permission_hub_address = "erd1qqqqqqqqqqqqqpgqsl0phg7xmzhqmk768h9agrrscgm7qwudd8ssls3aq2"
