contract_address = "erd1qqqqqqqqqqqqqpgqhy480yrhq4mahdqectaev8tp6les45v8d8ssswhu4q"
pair_address = "erd1qqqqqqqqqqqqqpgqu8tpc4gvvvm7sw9lclrhwfqzqcvm03had8sstnep4f"
energy_factory_address = "erd1qqqqqqqqqqqqqpgqhkwmac6hg3c54gf7wsl5zsqtd56fsg53d8ss78glqe"
lp_farm_address = "erd1qqqqqqqqqqqqqpgqcqa23cldm4hwn9fsue47dkm5tplvd36vd8ssk9myt8"
farm_staking_address = "erd1qqqqqqqqqqqqqpgqh4un2kem399m4d6fm6y4k7q3vsg5ft2rd8ssj6c7n6"
permission_hub_address = "erd1qqqqqqqqqqqqqpgqtu5737h87k40d97p3r0mangahl25sjwnd8ss3qxmj0"
energy_factory_mock_address = "erd1qqqqqqqqqqqqqpgqcpkrzt5x3nptg8289nhswh4jdp45fqp4d8ss02vgnf"
