contract_address = "erd1qqqqqqqqqqqqqpgqefy76ak50ftmhhmnx2eyu4xfy4456guqd8ssp7grzv"
pair_address = "erd1qqqqqqqqqqqqqpgqsn6ha6n35h4q0tccy7vlhmyu4zldvvzjd8ssz7utt4"
energy_factory_address = "erd1qqqqqqqqqqqqqpgq9qdvw20fwnmen8v2f20xcwuq9vwu45dud8ss8t2qr0"
lp_farm_address = "erd1qqqqqqqqqqqqqpgqsxympcgzsl74430xpwpvgtrvk7zeh79sd8ssaprwlh"
farm_staking_address = "erd1qqqqqqqqqqqqqpgq8x37pvnltctc5zvk24ly8a7uryqat6jyd8ssdq305r"
permission_hub_address = "erd1qqqqqqqqqqqqqpgqpz93fwpkj0sakw4mh9m5tmm00zg30phgd8ss9prn40"
