contract_address = "erd1qqqqqqqqqqqqqpgqq2f980jl0mf22mda8zzh8fpt6d6rrzw2d8ssdx9d99"
pair_address = "erd1qqqqqqqqqqqqqpgq7q3my2qpy7v9ce88l55svvevjgnn2uvqd8ss0qp7ac"
energy_factory_address = "erd1qqqqqqqqqqqqqpgqkujvdawtfz52xdz74wwp7ar5fndrw8g3d8ss27am8h"
farm_address = "erd1qqqqqqqqqqqqqpgqu4gtjupj3w5j26pudctstejc206zwg0ed8ss967hwl"
farm_staking_address = "erd1qqqqqqqqqqqqqpgqnpa0lw8j32858wlrwkwdphyw7s6yk35wd8ssctl0y0"
permission_hub_address = "erd1qqqqqqqqqqqqqpgqtu5737h87k40d97p3r0mangahl25sjwnd8ss3qxmj0"
locked_asset_factory_address = "erd1qqqqqqqqqqqqqpgq4ym6w7ntw2m6vtkcx433vw989xpufrfud8ssjjfey6"
router_address = "erd1qqqqqqqqqqqqqpgqemsdrp9fyhsp2xjvn7l5kg6nkty6kwwwd8ssc8vwh2"
